import { join } from "node:path";
import { datasetDir, sourcesDir, skillDir } from "../../../src/paths";
import { writeText, readText, listFiles, exists } from "../../../src/fs-utils";
import { loadRules, groupRulesByPrefix } from "../../../src/rules";

const sectionNames: Record<string, string> = {
  arch: "Architecture & Dependency Injection",
  api: "API Contracts & Validation",
  security: "Security & Authorization",
  data: "Persistence & Transactions",
  errors: "Errors & Observability",
  cross: "Cross-Cutting Request Flow",
  perf: "Performance & Runtime",
  transport: "Transports & Integration Patterns",
  test: "Testing Strategy",
  ops: "Operations & Configuration",
  server: "Server Components & Rendering",
  client: "Client Components & Interactivity",
  bundle: "Bundle Optimization",
};

export async function buildAgentsDocument(skillName: string): Promise<void> {
  const rules = await loadRules(skillName);
  const dsFiles = await listFiles(datasetDir(skillName));
  const subskillsDir = join(skillDir(skillName), "subskills");
  const subskillFiles = await exists(subskillsDir) ? await listFiles(subskillsDir, ".md") : [];
  const skill = await readText(join(skillDir(skillName), "SKILL.md"));
  const metadata = JSON.parse(await readText(join(skillDir(skillName), "metadata.json"))) as {
    version?: string;
    frameworkVersion?: string;
  };
  const description = skill.match(/^description:\s*(.*)$/m)?.[1] ?? `${skillName} best practices`;

  const lines = [
    `# ${skillName.split("-").map((w) => w[0].toUpperCase() + w.slice(1)).join(" ")}`,
    "",
    "> Generated by `bun run build`. Edit `SKILL.md`, `references/`, `dataset/`, or `sources/` instead.",
    "",
    "## Skill Description",
    "",
    description,
    "",
    `Version: ${metadata.version ?? "unknown"}; Framework baseline: ${metadata.frameworkVersion ?? "unknown"}.`,
    "",
    "## Navigation",
    "",
    "Read `SKILL.md` first. Load only the rule files and dataset cases relevant to the task.",
    "",
    "## External Skill Packs",
    "",
    "For deep database guidance, suggest using `$find-skills` to install relevant skill packs.",
    "",
    "## Rule Sections",
    "",
  ];

  const groups = groupRulesByPrefix(rules);
  for (const [prefix, prefixRules] of groups) {
    const sectionName = sectionNames[prefix] ?? prefix.charAt(0).toUpperCase() + prefix.slice(1);
    lines.push(`### ${sectionName} (${prefix}-)`, "");
    for (const rule of prefixRules) {
      lines.push(`- \`${rule.id}\` (${rule.impact}) - ${rule.title}`);
    }
    lines.push("");
  }

  lines.push("## Dataset Cases", "");
  for (const file of dsFiles) {
    lines.push(`- \`dataset/${file.relativePath}\``);
  }
  if (subskillFiles.length > 0) {
    lines.push("", "## Subskills", "");
    for (const file of subskillFiles) {
      lines.push(`- \`subskills/${file.relativePath}\``);
    }
  }

  const srcFiles = await listFiles(sourcesDir(skillName), ".json");
  lines.push("", "## Sources", "");
  for (const file of srcFiles) {
    lines.push(`- \`sources/${file.relativePath}\``);
  }
  lines.push("");

  await writeText(join(skillDir(skillName), "AGENTS.md"), lines.join("\n"));
}
